# Generated by Django 5.2 on 2025-04-14 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['full_name'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Contrato'),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='En cm', null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='player',
            name='market_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor de Mercado'),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('Derecho', 'Derecho'), ('Izquierdo', 'Izquierdo'), ('Ambidiestro', 'Ambidiestro')], max_length=20, verbose_name='Pie Preferido'),
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Valoración General'),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='En kg', null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='report',
            name='potential_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Potencial'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Evento/Partido'),
        ),
        migrations.AddField(
            model_name='report',
            name='strengths',
            field=models.TextField(blank=True, verbose_name='Fortalezas'),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=255, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='weaknesses',
            field=models.TextField(blank=True, verbose_name='Debilidades'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_club',
            field=models.CharField(blank=True, max_length=150, verbose_name='Club Actual'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Posición Principal'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='report',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.player', verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='report',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Valoración (1-5)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Técnico', 'Técnico'), ('Táctico', 'Táctico'), ('Físico', 'Físico'), ('Psicológico', 'Psicológico'), ('Partido', 'Partido'), ('Potencial', 'Potencial'), ('Completo', 'Completo'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Informe'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Resumen Ejecutivo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del Informe'),
        ),
    ]
