# Generated by Django 5.2 on 2025-04-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_options_alter_report_options_player_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agilidad',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Agilidad'),
        ),
        migrations.AddField(
            model_name='player',
            name='anticipacion',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Anticipación'),
        ),
        migrations.AddField(
            model_name='player',
            name='control',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Control Balón'),
        ),
        migrations.AddField(
            model_name='player',
            name='decision',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Decisiones'),
        ),
        migrations.AddField(
            model_name='player',
            name='finalizacion',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Finalización'),
        ),
        migrations.AddField(
            model_name='player',
            name='fuerza',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Fuerza'),
        ),
        migrations.AddField(
            model_name='player',
            name='pase_corto',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Pase Corto'),
        ),
        migrations.AddField(
            model_name='player',
            name='posicionamiento',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Posicionamiento'),
        ),
        migrations.AddField(
            model_name='player',
            name='regate',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Regate'),
        ),
        migrations.AddField(
            model_name='player',
            name='resistencia',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Resistencia'),
        ),
        migrations.AddField(
            model_name='player',
            name='salto',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Salto'),
        ),
        migrations.AddField(
            model_name='player',
            name='tiro_lejano',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Tiro Lejano'),
        ),
        migrations.AddField(
            model_name='player',
            name='trabajo',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Ritmo Trabajo'),
        ),
        migrations.AddField(
            model_name='player',
            name='velocidad',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Velocidad'),
        ),
        migrations.AddField(
            model_name='player',
            name='vision',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Visión Juego'),
        ),
    ]
