# Generated by Django 5.2 on 2025-04-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_agilidad_player_anticipacion_player_control_and_more'),
    ]

    operations = [
    ]
