# Generated by Django 5.2 on 2025-04-19 21:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_force_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_club',
        ),
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='player',
            name='finalizacion',
        ),
        migrations.RemoveField(
            model_name='player',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pase_corto',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='salto',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tiro_lejano',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='potential_notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='player',
            name='contract_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='entradas',
            field=models.PositiveIntegerField(default=50, help_text='Tackling (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='liderazgo',
            field=models.PositiveIntegerField(default=50, help_text='Leadership (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='marcaje',
            field=models.PositiveIntegerField(default=50, help_text='Marking (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pase',
            field=models.PositiveIntegerField(default=50, help_text='Passing (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='penales',
            field=models.PositiveIntegerField(default=50, help_text='Penalties (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='potencia_tiro',
            field=models.PositiveIntegerField(default=50, help_text='Shot Power (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='precision_tiro',
            field=models.PositiveIntegerField(default=50, help_text='Shooting Accuracy (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='remate_cabeza',
            field=models.PositiveIntegerField(default=50, help_text='Heading Accuracy (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='saques_banda',
            field=models.PositiveIntegerField(default=50, help_text='Throw-ins (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='talento',
            field=models.PositiveIntegerField(default=50, help_text='Flair/Talent (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='tiros_lejanos',
            field=models.PositiveIntegerField(default=50, help_text='Long Shots (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='tiros_libres',
            field=models.PositiveIntegerField(default=50, help_text='Free Kicks (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='trabajo_equipo',
            field=models.PositiveIntegerField(default=50, help_text='Teamwork (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='vision_juego',
            field=models.PositiveIntegerField(default=50, help_text='Vision (0-100)'),
        ),
        migrations.AddField(
            model_name='player',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='detailed_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='match_observed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='overall_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Overall rating (1-10 or 1-100)', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='potential_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Potential rating', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='agilidad',
            field=models.PositiveIntegerField(default=50, help_text='Agility (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='anticipacion',
            field=models.PositiveIntegerField(default=50, help_text='Anticipation (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='control',
            field=models.PositiveIntegerField(default=50, help_text='Ball Control (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fuerza',
            field=models.PositiveIntegerField(default=50, help_text='Strength (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated market value in EUR', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='posicionamiento',
            field=models.PositiveIntegerField(default=50, help_text='Positioning (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa Central'), ('LI', 'Lateral Izquierdo'), ('LD', 'Lateral Derecho'), ('MC', 'Mediocentro'), ('MCD', 'Mediocentro Defensivo'), ('MCO', 'Mediocentro Ofensivo'), ('EI', 'Extremo Izquierdo'), ('ED', 'Extremo Derecho'), ('DC', 'Delantero Centro'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('Right', 'Right'), ('Left', 'Left'), ('Both', 'Both')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='regate',
            field=models.PositiveIntegerField(default=50, help_text='Dribbling (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='resistencia',
            field=models.PositiveIntegerField(default=50, help_text='Stamina (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='velocidad',
            field=models.PositiveIntegerField(default=50, help_text='Speed (0-100)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.player'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Scout', 'Scout'), ('Admin', 'Admin'), ('Viewer', 'Viewer')], default='Viewer', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
