# Generated by Django 5.2 on 2025-04-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_alter_player_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('', '---------'), ('GK', 'Goalkeeper (GK)'), ('CB', 'Centre Back (CB)'), ('LB', 'Left Back (LB)'), ('RB', 'Right Back (RB)'), ('LWB', 'Left Wing Back (LWB)'), ('RWB', 'Right Wing Back (RWB)'), ('CDM', 'Defensive Midfielder (CDM)'), ('CM', 'Central Midfielder (CM)'), ('LM', 'Left Midfielder (LM)'), ('RM', 'Right Midfielder (RM)'), ('CAM', 'Attacking Midfielder (CAM)'), ('LW', 'Left Winger (LW)'), ('RW', 'Right Winger (RW)'), ('CF', 'Centre Forward (CF)'), ('ST', 'Striker (ST)')], default='', max_length=50),
        ),
    ]
