# Generated by Django 5.2 on 2025-04-20 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Posición')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name'], 'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil Usuario', 'verbose_name_plural': 'Perfiles Usuarios'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Nacimiento'),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='player',
            name='market_value_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='EUR', max_length=3, verbose_name='Moneda Valor Mercado'),
        ),
        migrations.AlterField(
            model_name='player',
            name='agilidad',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Agilidad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='anticipacion',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Anticipación'),
        ),
        migrations.AlterField(
            model_name='player',
            name='contract_until',
            field=models.DateField(blank=True, null=True, verbose_name='Contrato Hasta'),
        ),
        migrations.AlterField(
            model_name='player',
            name='control',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Control'),
        ),
        migrations.AlterField(
            model_name='player',
            name='entradas',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Entradas'),
        ),
        migrations.AlterField(
            model_name='player',
            name='fuerza',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Fuerza'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Altura en cm', null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='liderazgo',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Liderazgo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='marcaje',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Marcaje'),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor numérico completo (ej: 50000, 1500000)', max_digits=15, null=True, verbose_name='Valor de Mercado'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pase',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Pase'),
        ),
        migrations.AlterField(
            model_name='player',
            name='penales',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Penales'),
        ),
        migrations.AlterField(
            model_name='player',
            name='posicionamiento',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Posicionamiento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='potencia_tiro',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Potencia Tiro'),
        ),
        migrations.AlterField(
            model_name='player',
            name='precision_tiro',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Precisión Tiro'),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('Right', 'Derecho'), ('Left', 'Izquierdo'), ('Both', 'Ambidiestro')], max_length=10, null=True, verbose_name='Pie Preferido'),
        ),
        migrations.AlterField(
            model_name='player',
            name='regate',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Regate'),
        ),
        migrations.AlterField(
            model_name='player',
            name='remate_cabeza',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Remate Cabeza'),
        ),
        migrations.AlterField(
            model_name='player',
            name='resistencia',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Resistencia'),
        ),
        migrations.AlterField(
            model_name='player',
            name='saques_banda',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Saques Banda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name='Fortalezas'),
        ),
        migrations.AlterField(
            model_name='player',
            name='talento',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Talento'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tiros_lejanos',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Tiros Lejanos'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tiros_libres',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Tiros Libres'),
        ),
        migrations.AlterField(
            model_name='player',
            name='trabajo_equipo',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Trabajo Equipo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='velocidad',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Velocidad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vision_juego',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Visión Juego'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weaknesses',
            field=models.TextField(blank=True, null=True, verbose_name='Debilidades'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en kg', null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='players', to='api.position', verbose_name='Posiciones'),
        ),
    ]
