# Generated by Django 5.2 on 2025-05-26 00:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_player_positions_player_position1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='player',
            name='agency_representing',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Agencia Representante'),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Contrato Vigente'), ('LOANED_OUT', 'Cedido (Saliendo)'), ('LOANED_IN', 'Cedido (Llegando)'), ('RENEWAL_PROCESS', 'En Proceso de Renovación'), ('EXPIRING_SOON', 'Contrato por Expirar'), ('FREE_AGENT', 'Agente Libre'), ('ACADEMY', 'Cantera/Formación'), ('OTHER', 'Otro')], max_length=20, null=True, verbose_name='Estado Contractual'),
        ),
        migrations.AddField(
            model_name='player',
            name='loan_destination_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_loaned_to_this_team', to='api.team', verbose_name='Equipo Destino (Si está cedido A este equipo)'),
        ),
        migrations.AddField(
            model_name='player',
            name='loan_origin_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_loaned_from_this_team', to='api.team', verbose_name='Equipo Propietario (Si está cedido EN este equipo)'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_specialization',
            field=models.CharField(choices=[('SCOUT', 'Scouting General'), ('NUTRITION', 'Nutrición'), ('PHYSIO', 'Fisioterapia'), ('TRAINING', 'Entrenamiento Deportivo'), ('MEDICAL', 'Medicina del Deporte'), ('PSYCHOLOGY', 'Psicología Deportiva'), ('EDUCATION', 'Educación'), ('SUMMARY', 'Informe Completo de Resumen')], default='SCOUT', max_length=20, verbose_name='Especialización del Informe'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary_report_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'report_specialization': 'SUMMARY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialized_reports', to='api.report', verbose_name='Informe de Resumen Padre'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='api.team', verbose_name='Equipo Actual'),
        ),
        migrations.AlterField(
            model_name='report',
            name='detailed_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Detalladas / Contenido Específico'),
        ),
        migrations.AlterField(
            model_name='report',
            name='match_observed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Partido/Evento Observado'),
        ),
        migrations.AlterField(
            model_name='report',
            name='overall_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Valoración general (ej: 1-100)', null=True, verbose_name='Valoración General'),
        ),
        migrations.AlterField(
            model_name='report',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.player', verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='report',
            name='potential_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Valoración de potencial (ej: 1-100)', null=True, verbose_name='Valoración Potencial'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Informe'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Autor del Informe'),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(verbose_name='Resumen Principal / Observaciones Clave'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SCOUT', 'Scout'), ('NUTRITIONIST', 'Nutricionista'), ('PHYSIOTHERAPIST', 'Fisioterapeuta'), ('TRAINING_SPECIALIST', 'Especialista en Entrenamiento'), ('SPORTS_MEDIC', 'Médico Deportivo'), ('SPORTS_PSYCHOLOGIST', 'Psicólogo Deportivo'), ('EDUCATOR', 'Educador/Tutor'), ('ADMIN', 'Administrador'), ('TEAM_STAFF', 'Staff de Equipo (General)'), ('VIEWER', 'Observador')], default='VIEWER', max_length=30, verbose_name='Rol Principal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.team', verbose_name='Equipo Afiliado'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Oferta')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida Hasta')),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Salario')),
                ('salary_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3, null=True, verbose_name='Moneda Salario')),
                ('contract_duration_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duración Contrato (Años)')),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cláusula/Precio Transferencia')),
                ('fee_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3, null=True, verbose_name='Moneda Cláusula')),
                ('clauses', models.TextField(blank=True, help_text='Cláusulas especiales, bonus, etc.', verbose_name='Cláusulas y Condiciones')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada a Agencia/Jugador'), ('VIEWED', 'Vista por Agencia/Jugador'), ('NEGOTIATING', 'En Negociación'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('WITHDRAWN', 'Retirada por Equipo'), ('EXPIRED', 'Expirada')], default='DRAFT', max_length=20, verbose_name='Estado de la Oferta')),
                ('is_counter_offer', models.BooleanField(default=False, verbose_name='Es Contraoferta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made_by_team', to='api.team', verbose_name='Equipo Ofertante')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='api.player', verbose_name='Jugador Ofertado')),
                ('previous_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='api.offer', verbose_name='Oferta Anterior (si es contraoferta)')),
                ('responsible_user', models.ForeignKey(help_text='Usuario que registra la oferta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Oferta por Jugador',
                'verbose_name_plural': 'Ofertas por Jugadores',
                'ordering': ['-offer_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_attachments/', verbose_name='Archivo Adjunto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del Adjunto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.report', verbose_name='Informe Asociado')),
            ],
            options={
                'verbose_name': 'Adjunto de Informe',
                'verbose_name_plural': 'Adjuntos de Informes',
            },
        ),
        migrations.CreateModel(
            name='PlayerHistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
                ('velocidad', models.PositiveIntegerField(blank=True, null=True)),
                ('resistencia', models.PositiveIntegerField(blank=True, null=True)),
                ('finalizacion', models.PositiveIntegerField(blank=True, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre este snapshot de datos')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='api.player')),
            ],
            options={
                'verbose_name': 'Dato Histórico de Jugador',
                'verbose_name_plural': 'Datos Históricos de Jugadores',
                'ordering': ['player', '-date_recorded'],
                'unique_together': {('player', 'date_recorded')},
            },
        ),
        migrations.CreateModel(
            name='PlayerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRACKING', 'Seguimiento Activo'), ('CONTACTED_AGENCY', 'Agencia Contactada'), ('NEGOTIATING', 'En Negociación'), ('RESERVED', 'Reservado (Intención Formal)'), ('CLOSED_LOST', 'Interés Perdido/Cerrado')], default='TRACKING', max_length=20, verbose_name='Estado del Interés')),
                ('interest_level', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Nivel de interés (1-5)', null=True, verbose_name='Nivel de Interés')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_party_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_interests_made', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Interesado (Scout)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to='api.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Interés en Jugador',
                'verbose_name_plural': 'Intereses en Jugadores',
                'ordering': ['-created_at'],
                'unique_together': {('player', 'interested_party_user')},
            },
        ),
    ]
