# Generated by Django 5.2 on 2025-05-26 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_report_options_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhistoricaldata',
            name='finalizacion',
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Logo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offering_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='api.team', verbose_name='Equipo Ofertante'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='Usuario que registra/gestiona la oferta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('VIEWED', 'Vista'), ('NEGOTIATING', 'En Negociación'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('WITHDRAWN', 'Retirada'), ('EXPIRED', 'Expirada')], default='DRAFT', max_length=20, verbose_name='Estado de la Oferta'),
        ),
        migrations.AlterField(
            model_name='player',
            name='contract_until',
            field=models.DateField(blank=True, null=True, verbose_name='Contrato Válido Hasta'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen del Jugador'),
        ),
        migrations.AlterField(
            model_name='player',
            name='loan_destination_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_loaned_to_here', to='api.team', verbose_name='Equipo Destino (Si está cedido A este equipo)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='loan_origin_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_loaned_from_here', to='api.team', verbose_name='Equipo Propietario (Si está cedido EN este equipo)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor numérico (ej: 50000.00)', max_digits=15, null=True, verbose_name='Valor de Mercado'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Jugador Sin Nombre', max_length=100, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name='Fortalezas (texto descriptivo)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='talento',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Talento/Creatividad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weaknesses',
            field=models.TextField(blank=True, null=True, verbose_name='Debilidades (texto descriptivo)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Informe/Evento'),
        ),
        migrations.AlterField(
            model_name='report',
            name='scout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Autor del Informe'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía Corta'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='api.team', verbose_name='Equipo Afiliado'),
        ),
    ]
