# Generated by Django 5.2.1 on 2025-05-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_playerhistoricaldata_finalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='anticipacion',
            field=models.PositiveIntegerField(blank=True, help_text='(0-100)', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='control',
            field=models.PositiveIntegerField(blank=True, help_text='(0-100)', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Altura en cm', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='pase',
            field=models.PositiveIntegerField(blank=True, help_text='(0-100)', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='posicionamiento',
            field=models.PositiveIntegerField(blank=True, help_text='(0-100)', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='precision_tiro',
            field=models.PositiveIntegerField(blank=True, help_text='(0-100)', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='vision_juego',
            field=models.PositiveIntegerField(blank=True, help_text='(0-100)', null=True),
        ),
        migrations.AddField(
            model_name='playerhistoricaldata',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en kg', null=True),
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin (si aplica)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas (ej: tipo de traspaso, cesión)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='api.player', verbose_name='Jugador')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Historial de Equipo del Jugador',
                'verbose_name_plural': 'Historiales de Equipos de Jugadores',
                'ordering': ['-start_date', '-end_date'],
                'unique_together': {('player', 'team', 'start_date')},
            },
        ),
    ]
