# Generated by Django 5.2.1 on 2025-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_playerhistoricaldata_anticipacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aceleracion_0_20m_secs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Aceleración 0-20m (s)'),
        ),
        migrations.AddField(
            model_name='player',
            name='agilidad_t_test_secs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Agilidad T-Test (s)'),
        ),
        migrations.AddField(
            model_name='player',
            name='agresividad',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Agresividad (Deportiva)'),
        ),
        migrations.AddField(
            model_name='player',
            name='asistencias_365',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Asistencias (últimos 365 días)'),
        ),
        migrations.AddField(
            model_name='player',
            name='cambio_direccion_5105_secs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cambio de Dirección 5-10-5 (s)'),
        ),
        migrations.AddField(
            model_name='player',
            name='compostura',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Compostura'),
        ),
        migrations.AddField(
            model_name='player',
            name='concentracion',
            field=models.PositiveIntegerField(default=50, help_text='(0-100)', verbose_name='Concentración'),
        ),
        migrations.AddField(
            model_name='player',
            name='distancia_media_km_90min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Distancia Media Recorrida (km/90min)'),
        ),
        migrations.AddField(
            model_name='player',
            name='evaluacion_equilibrio_dinamico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Evaluación Equilibrio Dinámico (ej: Bueno, Necesita Mejora)'),
        ),
        migrations.AddField(
            model_name='player',
            name='evaluacion_equilibrio_estatico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Evaluación Equilibrio Estático (ej: Bueno, Necesita Mejora)'),
        ),
        migrations.AddField(
            model_name='player',
            name='fuerza_relativa_1rm_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Fuerza Relativa 1RM (ratio peso corporal)'),
        ),
        migrations.AddField(
            model_name='player',
            name='goles_365',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles (últimos 365 días)'),
        ),
        migrations.AddField(
            model_name='player',
            name='partidos_jugados_365',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Partidos Jugados (últimos 365 días)'),
        ),
        migrations.AddField(
            model_name='player',
            name='pases_completados_pct_365',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Pases Completados (últimos 365 días)'),
        ),
        migrations.AddField(
            model_name='player',
            name='potencia_pico_w_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Potencia Pico (W/kg)'),
        ),
        migrations.AddField(
            model_name='player',
            name='regates_per_90_365',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Regates Exitosos por 90 min (últimos 365 días)'),
        ),
        migrations.AddField(
            model_name='player',
            name='salto_horizontal_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Salto Horizontal (m)'),
        ),
        migrations.AddField(
            model_name='player',
            name='velocidad_max_kmh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Velocidad Máxima (km/h)'),
        ),
        migrations.AddField(
            model_name='player',
            name='vo2_max_ml_kg_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='VO2 Máx (ml/kg/min)'),
        ),
        migrations.AddField(
            model_name='player',
            name='xg_per_90_365',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='xG por 90 min (últimos 365 días)'),
        ),
        migrations.AddField(
            model_name='player',
            name='yoyo_ir1_level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Yo-Yo IR1 Nivel (ej: 18.5)'),
        ),
    ]
