"""
Django settings for scoutpro360_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # <--- ASEGÚRATE DE QUE ESTA LÍNEA ESTÉ PRESENTE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qnq-(jewq1=q+-f643)kql2a&8@3j4rl7$a$kw1#&vdoa@9xsy(oq6' # Asegúrate que esta sea tu clave

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Cambiar a False en producción

# Configurar hosts permitidos en producción
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Apps de Django por defecto
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework', # Django REST Framework
    'corsheaders',    # Para permitir peticiones desde el frontend
    'django_filters', # Para filtros avanzados en la API

    # Your apps
    'api', # Tu app de API donde están los modelos, vistas, etc.
]

MIDDLEWARE = [
    # CORS Middleware debe ir lo más arriba posible, especialmente antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scoutpro360_backend.urls' # Archivo principal de URLs

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Directorios adicionales para plantillas (si usas Django Templates)
        'APP_DIRS': True, # Busca plantillas dentro de las apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoutpro360_backend.wsgi.application' # Configuración para servidor WSGI


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'scoutpro360db',    # Nombre de tu base de datos
        'USER': 'postgres',         # Usuario de la base de datos
        'PASSWORD': 'Zeromon733*',  # Contraseña de la base de datos (¡Considera la seguridad!)
        'HOST': 'localhost',        # O la IP/dominio del servidor de BD
        'PORT': '5432',             # Puerto por defecto de PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # Puedes cambiarlo a 'es' si prefieres español por defecto

TIME_ZONE = 'UTC' # Zona horaria estándar

USE_I18N = True # Habilitar internacionalización

USE_TZ = True # Habilitar soporte para zonas horarias


# Static files (CSS, JavaScript, Images) - Servidos por Django en desarrollo
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # Para producción con collectstatic. Mantenlo comentado en desarrollo.


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS Configuration - Para permitir que tu frontend React se comunique con la API
# https://github.com/adamchainz/django-cors-headers
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Puerto por defecto de Create React App
    "http://localhost:5173", # Puerto por defecto de Vite
    # Añade aquí la URL de tu frontend si usa otro puerto o dominio
]
# Opcional: permitir credenciales (cookies, autenticación) si es necesario
# CORS_ALLOW_CREDENTIALS = True
# Opcional: permitir todos los orígenes (solo para desarrollo, ¡inseguro!)
# CORS_ALLOW_ALL_ORIGINS = True # Descomentar solo para desarrollo si es estrictamente necesario


# --- CONFIGURACIÓN DE DJANGO REST FRAMEWORK ---
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework.authentication.SessionAuthentication',
    #     'rest_framework.authentication.TokenAuthentication',
    # ],
}
# --- FIN CONFIGURACIÓN DRF ---


# --- INICIO: Configuración de Archivos Multimedia (Media Files) ---
# URL base desde donde se servirán los archivos multimedia.
MEDIA_URL = '/media/'

# Ruta absoluta en el sistema de archivos donde se guardarán los archivos subidos.
# BASE_DIR ya está definido arriba usando pathlib.Path
MEDIA_ROOT = BASE_DIR / 'media'

# Si prefieres usar os.path.join (asegúrate de tener 'import os' al principio):
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# --- FIN: Configuración de Archivos Multimedia ---